In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/dados.csv')

In [3]:
df.head()

  Sales Person  Country         Product        Date  Amount  Boxes Shipped
0    Ana Silva   Brasil      Amargo 70%  2026-01-05  1250.0             25
1   James Cook      USA  Milk Chocolate  2026-01-07   840.0             12
2  Elena Rossi    Italy    Gianduja Bar  2026-01-10  2100.0             30
3   Marc Petit   France    Truffles Box  2026-01-12   550.0              5
4  Hans Müller  Germany   Marzipan Dark  2026-01-15  1450.0             22

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   100 non-null    object
 1   Country        100 non-null    object
 2   Product        100 non-null    object
 3   Date           100 non-null    object
 4   Amount         100 non-null    float64
 5   Boxes Shipped  100 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [5]:
df.describe()

            Amount  Boxes Shipped
count   100.000000     100.000000
mean   1572.600000      23.240000
std     958.848868      11.868914
min     430.000000       4.000000
25%     742.500000      12.000000
50%    1265.000000      21.500000
75%    2262.500000      33.000000
max    4200.000000      52.000000

In [6]:
df.isnull().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64